### ISSUE TITLE
Meson as build system?

### ISSUE THREAD

**Issue by simonspa** [Monochrome-Sauce/sublime-meson#5]
Is there a way I can use the Meson package to set up a build system? I know I can run the `Meson: Compile` command from the command palette, but it would be great to have it available as build system directly.

**Comment by Monochrome-Sauce** [comment]
Do you mean a command for creating a basic `meson.build` file?

**Comment by simonspa** [comment]
Hm, no, I meant somehow integrating it with the build systems Sublime Text provides, here:

![image](https://github.com/Monochrome-Sauce/sublime-meson/assets/1677436/6c355091-a5cb-45fa-bc6b-99507cbd31d6)

I do know that this can somehow be described in the `.sublime-project` file for each project but I don't know the mechanics. Some of it is documented here: https://www.sublimetext.com/docs/build_systems.html

**Comment by Monochrome-Sauce** [comment]
Sorry for the wait. I added `compile` and `setup` as build systems that only exist when there's a `meson.build` file present in the project directory.

I will not close the issue until I hear back that it works for you.

**Comment by simonspa** [comment]
Dear @Monochrome-Sauce,

thank you so much - this is working like a charm:

![image](https://github.com/Monochrome-Sauce/sublime-meson/assets/1677436/711d96a5-f087-4a7c-814e-534d671cc2fb)

Really, really appreciated! 

One idea for improvement would be the possibility to configure the target build directory, mostly so I can switch seamlessly between console and Sublime compilation with the same muscle memory - but also to avoid potential clashes between the hardcoded path and directories existing in the repository.

All the best!

**Comment by simonspa** [comment]
...and for a future improvement, a support for build error annotations would be the cherry on the cake:

![image](https://github.com/Monochrome-Sauce/sublime-meson/assets/1677436/a3101bff-e5a0-4509-8fc3-8e1e8a348918)

If you don't have the time for this, I might look into understanding the workings of this!

**Comment by simonspa** [comment]
...see #6 - was as simple as including a regex to match error lines.
